CREATE TABLE Compra (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codproduto INT NOT NULL,
	nome VARCHAR(50) NOT NULL,
	fornecedor VARCHAR(50) NOT NULL,
	valor DECIMAL(10, 2) NOT NULL,
	data DATE NOT NULL,
	quantidade INT NOT NULL
);
